use failure::Error;

pub fn search() -> Result<(), Error> {
    println!("search!");
    Ok(())
}
